### ISSUE TITLE
Plugins command and flake8-comprehensions

### ISSUE THREAD

**Issue by AlwxSin** [life4/flakehell#27]
By running `flakehell plugins` I've got an exception

```python
Traceback (most recent call last):
  File "project_folder/.venv/bin/flakehell", line 10, in <module>
    sys.exit(entrypoint())
  File "project_folder/.venv/lib/python3.7/site-packages/flakehell/_cli.py", line 39, in entrypoint
    exit_code, msg = main(argv)
  File "project_folder/.venv/lib/python3.7/site-packages/flakehell/_cli.py", line 31, in main
    return COMMANDS[command_name](argv=argv[1:])
  File "project_folder/.venv/lib/python3.7/site-packages/flakehell/commands/_plugins.py", line 18, in plugins_command
    version_width = min(8, max(len(p['version']) for p in plugins))
  File "project_folder/.venv/lib/python3.7/site-packages/flakehell/commands/_plugins.py", line 18, in <genexpr>
    version_width = min(8, max(len(p['version']) for p in plugins))
TypeError: object of type 'cached_property' has no len()
```

The problem is in `flake8-comprehensions`. It looks like
```python
{'type': 'ast_plugins',
  'name': 'flake8-comprehensions',
  'codes': ['C4'],
  'version': <cached_property.cached_property at 0x11353e290>}
```

**Comment by orsinium** [comment]
Thank you for your report! They fixed it in https://github.com/adamchainz/flake8-comprehensions/pull/187. Please, update flake8-comprehensions to 3.0.1.
