### ISSUE TITLE
base pyproject.toml from URL doesnt work in windows

### ISSUE THREAD

**Issue by kwint** [life4/flakehell#51]
We want to use the base function of flakehell, where a piece of the pyproject.toml settings is somewhere in the cloud. This works perfectly fine on Ubuntu (WSL), but fails on windows.
```
Traceback (most recent call last):
  File "C:\Users\Quint\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Quint\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Quint\code\metal-core\venv\Scripts\flakehell.exe\__main__.py", line 9, in <module>
  File "c:\users\quint\code\metal-core\venv\lib\site-packages\flakehell\_cli.py", line 39, in entrypoint
    exit_code, msg = main(argv)
  File "c:\users\quint\code\metal-core\venv\lib\site-packages\flakehell\_cli.py", line 31, in main
    return COMMANDS[command_name](argv=argv[1:])
  File "c:\users\quint\code\metal-core\venv\lib\site-packages\flakehell\commands\_plugins.py", line 13, in plugins_command
    plugins = sorted(get_installed(app=app), key=lambda p: p['name'])
  File "c:\users\quint\code\metal-core\venv\lib\site-packages\flakehell\_logic\_discover.py", line 25, in get_installed
    app.initialize([])
  File "c:\users\quint\code\metal-core\venv\lib\site-packages\flake8\main\application.py", line 365, in initialize
    self.parse_configuration_and_cli(argv)
  File "c:\users\quint\code\metal-core\venv\lib\site-packages\flakehell\_patched\_app.py", line 58, in parse_configuration_and_cli            config.__dict__.update(self.get_toml_config(config_path))
  File "c:\users\quint\code\metal-core\venv\lib\site-packages\flakehell\_patched\_app.py", line 32, in get_toml_config
    return read_config(path)
  File "c:\users\quint\code\metal-core\venv\lib\site-packages\flakehell\_logic\_config.py", line 12, in read_config
    new_config = _read_local(path)
  File "c:\users\quint\code\metal-core\venv\lib\site-packages\flakehell\_logic\_config.py", line 23, in _read_local
    return _parse_config(stream.read())
  File "c:\users\quint\code\metal-core\venv\lib\site-packages\flakehell\_logic\_config.py", line 54, in _parse_config
    config = _merge_configs(read_config(*paths), config)
  File "c:\users\quint\code\metal-core\venv\lib\site-packages\flakehell\_logic\_config.py", line 13, in read_config
    elif Path(path).exists():
  File "C:\Users\Quint\AppData\Local\Programs\Python\Python38\lib\pathlib.py", line 1383, in exists
    self.stat()
  File "C:\Users\Quint\AppData\Local\Programs\Python\Python38\lib\pathlib.py", line 1189, in stat
    return self._accessor.stat(self)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'https:\\<hidden>\\pyproject.toml'
```

local pyproject.toml looks like this:
```
[tool.flakehell]
base = "https://<hidden>/pyproject.toml"
baseline = ".flakehell_baseline"
```

**Comment by orsinium** [comment]
Thank you for the report! Please, upgrade flakehell to 0.3.4.

**Comment by kwint** [comment]
Thanks for your work!
