### ISSUE TITLE
Syntax error on an ignored file

### ISSUE THREAD

**Issue by Dreamsorcerer** [life4/flakehell#54]
When running flakehell, I get the below error as it tries to process an encrypted file despite this being in the exclude list. The error doesn't occur when running flake8 without flakehell being installed.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/astroid/manager.py", line 229, in file_from_module_name
    value = self._mod_file_cache[(modname, contextfile)]
KeyError: ('secrets_vault.production', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/tokenize.py", line 385, in find_cookie
    line_string = line.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 10: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/flakehell", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.7/site-packages/flakehell/_cli.py", line 39, in entrypoint
    exit_code, msg = main(argv)
  File "/usr/local/lib/python3.7/site-packages/flakehell/_cli.py", line 31, in main
    return COMMANDS[command_name](argv=argv[1:])
  File "/usr/local/lib/python3.7/site-packages/flakehell/commands/_lint.py", line 11, in lint_command
    app.run(argv)
  File "/usr/local/lib/python3.7/site-packages/flake8/main/application.py", line 393, in run
    self._run(argv)
  File "/usr/local/lib/python3.7/site-packages/flake8/main/application.py", line 381, in _run
    self.run_checks()
  File "/usr/local/lib/python3.7/site-packages/flake8/main/application.py", line 300, in run_checks
    self.file_checker_manager.run()
  File "/usr/local/lib/python3.7/site-packages/flake8/checker.py", line 331, in run
    self.run_serial()
  File "/usr/local/lib/python3.7/site-packages/flake8/checker.py", line 315, in run_serial
    checker.run_checks()
  File "/usr/local/lib/python3.7/site-packages/flakehell/_patched/_checkers.py", line 193, in run_checks
    super().run_checks()
  File "/usr/local/lib/python3.7/site-packages/flake8/checker.py", line 598, in run_checks
    self.run_ast_checks()
  File "/usr/local/lib/python3.7/site-packages/flake8/checker.py", line 502, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "/usr/local/lib/python3.7/site-packages/flakehell/plugins/_pylint.py", line 40, in run
    Run([self.filename], reporter=reporter, do_exit=False)
  File "/usr/local/lib/python3.7/site-packages/pylint/lint/run.py", line 344, in __init__
    linter.check(args)
  File "/usr/local/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 871, in check
    self.get_ast, self._iterate_file_descrs(files_or_modules)
  File "/usr/local/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 904, in _check_files
    self._check_file(get_ast, check_astroid_module, name, filepath, modname)
  File "/usr/local/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 930, in _check_file
    check_astroid_module(ast_node)
  File "/usr/local/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 1063, in check_astroid_module
    ast_node, walker, rawcheckers, tokencheckers
  File "/usr/local/lib/python3.7/site-packages/pylint/lint/pylinter.py", line 1107, in _check_astroid_module
    walker.walk(ast_node)
  File "/usr/local/lib/python3.7/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    self.walk(child)
  File "/usr/local/lib/python3.7/site-packages/pylint/utils/ast_walker.py", line 72, in walk
    callback(astroid)
  File "/usr/local/lib/python3.7/site-packages/pylint/checkers/variables.py", line 1177, in visit_import
    module = next(_infer_name_module(node, parts[0]))
  File "/usr/local/lib/python3.7/site-packages/astroid/util.py", line 160, in limit_inference
    yield from islice(iterator, size)
  File "/usr/local/lib/python3.7/site-packages/astroid/context.py", line 113, in cache_generator
    for result in generator:
  File "/usr/local/lib/python3.7/site-packages/astroid/decorators.py", line 132, in raise_if_nothing_inferred
    yield next(generator)
  File "/usr/local/lib/python3.7/site-packages/astroid/decorators.py", line 96, in wrapped
    res = next(generator)
  File "/usr/local/lib/python3.7/site-packages/astroid/inference.py", line 254, in infer_import
    yield self.do_import_module(name)
  File "/usr/local/lib/python3.7/site-packages/astroid/mixins.py", line 100, in do_import_module
    modname, level=level, relative_only=level and level >= 1
  File "/usr/local/lib/python3.7/site-packages/astroid/scoped_nodes.py", line 642, in import_module
    return MANAGER.ast_from_module_name(absmodname)
  File "/usr/local/lib/python3.7/site-packages/astroid/manager.py", line 189, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
  File "/usr/local/lib/python3.7/site-packages/astroid/manager.py", line 98, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "/usr/local/lib/python3.7/site-packages/astroid/builder.py", line 138, in file_build
    return self._post_build(module, encoding)
  File "/usr/local/lib/python3.7/site-packages/astroid/builder.py", line 155, in _post_build
    self.add_from_names_to_locals(from_node)
  File "/usr/local/lib/python3.7/site-packages/astroid/builder.py", line 209, in add_from_names_to_locals
    imported = node.do_import_module()
  File "/usr/local/lib/python3.7/site-packages/astroid/mixins.py", line 100, in do_import_module
    modname, level=level, relative_only=level and level >= 1
  File "/usr/local/lib/python3.7/site-packages/astroid/scoped_nodes.py", line 642, in import_module
    return MANAGER.ast_from_module_name(absmodname)
  File "/usr/local/lib/python3.7/site-packages/astroid/manager.py", line 145, in ast_from_module_name
    found_spec = self.file_from_module_name(modname, context_file)
  File "/usr/local/lib/python3.7/site-packages/astroid/manager.py", line 233, in file_from_module_name
    modname.split("."), context_file=contextfile
  File "/usr/local/lib/python3.7/site-packages/astroid/modutils.py", line 423, in file_info_from_modpath
    return _spec_from_modpath(modpath, path, context)
  File "/usr/local/lib/python3.7/site-packages/astroid/modutils.py", line 648, in _spec_from_modpath
    found_spec = spec.find_spec(modpath, path)
  File "/usr/local/lib/python3.7/site-packages/astroid/interpreter/_import/spec.py", line 337, in find_spec
    _path, modname, module_parts, processed, submodule_path or path
  File "/usr/local/lib/python3.7/site-packages/astroid/interpreter/_import/spec.py", line 300, in _find_spec_with_path
    spec = finder.find_module(modname, module_parts, processed, submodule_path)
  File "/usr/local/lib/python3.7/site-packages/astroid/interpreter/_import/spec.py", line 124, in find_module
    stream, mp_filename, mp_desc = imp.find_module(modname, submodule_path)
  File "/usr/local/lib/python3.7/imp.py", line 301, in find_module
    encoding = tokenize.detect_encoding(file.readline)[0]
  File "/usr/local/lib/python3.7/tokenize.py", line 426, in detect_encoding
    encoding = find_cookie(first)
  File "/usr/local/lib/python3.7/tokenize.py", line 390, in find_cookie
    raise SyntaxError(msg)
SyntaxError: invalid or missing encoding declaration for '/src/secrets_vault/production.py'
```

**Comment by Dreamsorcerer** [comment]
Also seems to only happen if the pylint plugin is enabled as well.

**Comment by orsinium** [comment]
How it is excluded? Please, attach the config and the command.

**Comment by Dreamsorcerer** [comment]
I've tried both exclude and extend-exclude in both .flake8 and pyproject.toml, and neither works. Here's a complete config (using the exclude version):

Command is just `flakehell lint`

```
[tool.flakehell]
builtins = ["_", "ngettext"]
enable-extensions = "G"
exclude = [".svn", "CVS", ".bzr", ".hg", ".git", "__pycache__", ".tox", "secrets_vault", ".pytest_cache"]
max-complexity = 7
max-doc-length = 120
max-line-length = 120
select = ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z","B901","B902","B903"]
ignore = ["ANN101","ANN102","D107","D203","D213","D406","D407","D408","D409","D413","E226","E722","I001","W503","WPS111","WPS210","WPS317","WPS318","WPS319","WPS432"]
suppress-none-returning = "True"
use_class_attributes_order_strict_mode = "True"
docstring-convention = "all"
eradicate-aggressive = "True"
application-import-names = ["environment","models","settings","web"]
import-order-style = "smarkets"
enable-extra-whitelist = "True"
inline-quotes = '"'
known-modules = ":[environment,models,settings,web]"
i-control-code = "True"
max-cognitive-score = 7
max-cognitive-average = 4
max-jones-score = 9
max-line-complexity = 14

[tool.flakehell.plugins]
flake8-aaa-checker = ["+*"]
flake8-annotations = ["+*"]
flake8-annotations-complexity = ["+*"]
flake8-assertive = ["+*"]
flake8-bandit = ["+*"]
flake8-broken-line = ["+*"]
flake8-bugbear = ["+*"]
flake8-class-attributes-order = ["+*"]
flake8-commas = ["+*"]
flake8-comprehensions = ["+*"]
flake8-darglint = ["+*"]
flake8-datetimez = ["+*"]
flake8-debugger = ["+*"]
flake8-docstrings = ["+*"]
flake8-eradicate = ["+*"]
flake8-executable = ["+*"]
flake8-import-order-flake8-linter = ["+*"]
flake8-isort = ["+*"]
flake8-logging-format = ["+*"]
flake8-quotes = ["+*"]
flake8-requirements = ["+*"]
flake8-rst-docstrings = ["+*"]
flake8-sorted-keys = ["+*"]
flake8-string-format = ["+*"]
flake8-todos = ["+*"]
mccabe = ["+*"]
pep8-naming = ["+*"]
pycodestyle = ["+*"]
pyflakes = ["+*"]
pylint = ["+*"]
wemake-python-styleguide = ["+*"]
```

**Comment by orsinium** [comment]
`exclude` should work. Please, check the latest version
