### ISSUE TITLE
Issue running with Docker

### ISSUE THREAD

**Issue by Phil-Barber** [life4/flakehell#55]
Hey so can get this to work locally. Tried adding to my docker build so I can run it on CI.

When `flakehell lint` is called I get the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/flakehell", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.6/site-packages/flakehell/_cli.py", line 39, in entrypoint
    exit_code, msg = main(argv)
  File "/usr/local/lib/python3.6/site-packages/flakehell/_cli.py", line 31, in main
    return COMMANDS[command_name](argv=argv[1:])
  File "/usr/local/lib/python3.6/site-packages/flakehell/commands/_lint.py", line 11, in lint_command
    app.run(argv)
  File "/usr/local/lib/python3.6/site-packages/flake8/main/application.py", line 360, in run
    self._run(argv)
  File "/usr/local/lib/python3.6/site-packages/flake8/main/application.py", line 347, in _run
    self.initialize(argv)
  File "/usr/local/lib/python3.6/site-packages/flake8/main/application.py", line 328, in initialize
    self.find_plugins(config_finder)
TypeError: find_plugins() takes 1 positional argument but 2 were given
make: *** [test] Error 1
```

Here is my `pip freeze` inside the docker container:
```
arrow==0.10.0
astor==0.8.1
astroid==2.4.1
atomicwrites==1.4.0
attrs==19.3.0
aws-xray-sdk==2.4.2
backcall==0.1.0
bandit==1.6.2
boto==2.41.0
botocore==1.16.7
certifi==2020.4.5.1
chardet==3.0.4
ciso8601==2.1.3
darglint==1.3.0
ddtrace==0.37.0
decorator==4.4.2
Django==1.9.7
django-crispy-forms==1.6.0
django-dirtyfields==1.4
django-extensions==1.7.0
django-filter==0.13.0
django-ical==1.5
django-model-utils==2.5
django-queryinspect==1.1.0
django-rest-swagger==0.3.8
djangorestframework==3.3.3
djangorestframework-filters==0.8.0
docutils==0.15.2
entrypoints==0.3
eradicate==1.0
factory-boy==2.7.0
fake-factory==0.5.7
flake8==3.8.1
flake8-bandit==2.1.2
flake8-broken-line==0.2.0
flake8-bugbear==19.8.0
flake8-commas==2.0.0
flake8-comprehensions==3.2.2
flake8-debugger==3.2.1
flake8-docstrings==1.5.0
flake8-eradicate==0.3.0
flake8-isort==2.9.1
flake8-polyfill==1.0.2
flake8-quotes==2.1.2
flake8-rst-docstrings==0.0.12
flake8-string-format==0.2.3
flakehell==0.3.3
Flask==0.10.1
Flask-API==0.6.7
freezegun==0.3.15
future==0.18.2
geopy==1.11.0
gevent==1.1.2
gitdb==4.0.5
GitPython==3.1.2
greenlet==0.4.15
gunicorn==19.6.0
hammock==0.2.4
hashids==1.1.0
hiredis==0.3.1
holidays==0.9.12
icalendar==4.0.6
ics==0.4
idna==2.8
importlib-metadata==1.6.0
ipdb==0.10.3
ipython==7.14.0
ipython-genutils==0.2.0
isort==4.3.21
itsdangerous==1.1.0
jedi==0.17.0
Jinja2==2.11.2
jmespath==0.9.5
jsonpickle==1.4.1
lazy-object-proxy==1.4.3
MarkupSafe==1.1.1
mccabe==0.6.1
mock==2.0.0
more-itertools==8.2.0
msgpack==1.0.0
packaging==20.3
parso==0.7.0
pathtools==0.1.2
pbr==5.4.5
pep8-naming==0.9.1
pexpect==4.8.0
pickleshare==0.7.5
piexif==1.0.5
Pillow==3.3.0
pluggy==0.13.1
ply==3.11
prometheus-client==0.0.19
prompt-toolkit==3.0.5
psycopg2==2.7.7
ptyprocess==0.6.0
py==1.8.1
py-zipkin==0.20.0
pycodestyle==2.6.0
pydocstyle==5.0.2
pyflakes==2.2.0
Pygments==2.6.1
pyinstrument==3.1.3
pyinstrument-cext==0.2.2
pylint==2.5.2
pymongo==3.10.1
pyparsing==2.4.7
pytest==5.2.4
python-dateutil==2.8.1
pytz==2016.4
PyYAML==5.3.1
raven==6.7.0
redis==2.10.6
reload==0.4
requests==2.22.0
requests-cache==0.4.12
requests-mock==1.0.0
restructuredtext-lint==1.3.0
simplejson==3.17.0
six==1.14.0
smmap==3.0.4
snowballstemmer==2.0.0
SQLAlchemy==1.0.14
stevedore==1.32.0
termcolor==1.1.0
testfixtures==6.14.1
thriftpy==0.3.9
thriftpy2==0.4.11
toml==0.10.0
traitlets==4.3.3
typed-ast==1.4.1
typing-extensions==3.7.4.2
urllib3==1.25.9
watchdog==0.10.2
wcwidth==0.1.9
wemake-python-styleguide==0.14.0
Werkzeug==1.0.1
whitenoise==3.3.1
wrapt==1.12.1
zipp==3.1.0
```

Here's the `ls -a` of the container
```
.                  api_function.py   pyproject.toml        run_api.sh
..                 app               queues.py             run_queues.sh
.baseline          entrypoint.py     queues_entrypoint.py  session
.reloadignore      gunicorn_conf.py  queues_function.py    session.egg-info
__init__.py        init.py           rate_rules            shift_swaps
api_entrypoint.py  manage.py         run.sh
```

And finally my pyproject.toml
```
[tool.flakehell]
# optionally inherit from remote config (or local if you want)
base = "https://raw.githubusercontent.com/life4/flakehell/master/pyproject.toml"
# specify any flake8 options. For example, exclude "example.py":
exclude = ["example.py"]
# make output nice
format = "grouped"
# 80 chars aren't enough in 21 century
max_line_length = 90
# show line of source code in output
show_source = true
baseline = ".baseline"

# list of plugins and rules for them
[tool.flakehell.plugins]
wemake-python-styleguide = ["+*"]
```

Let me know if you need any more info!

**Comment by jurasikasan** [comment]
Hello! I got the same problem with my CI.
Sharing workaround (just in case if it will be useful)
fragment of .gitlab.ci.yml:
```
  before_script:
    - python3 -m pip install flake8==3.7.9  # TODO workaround for https://github.com/life4/flakehell/issues/55
    - python3 -m pip install flakehell
  script:
    - flakehell lint
```
In my case flake8==3.7.9 is enough but here diff in versions I can see: 

last successful pipeline
flake8 3.7.9
pyflakes 2.1.1
pycodestyle 2.5.0

first failed
flake8 3.8.1
pyflakes 2.2.0
pycodestyle 2.6.0

**Comment by Phil-Barber** [comment]
@jurasikasan thank you! this fixed the config issue.
I'm getting a second issue in that it isn't reading the baseline from my pyproject.toml (which is present in the container)
But I'll keep fiddling and perhaps open a new issue if I need to

**Comment by Phil-Barber** [comment]
OK yeah so now - flakehell is up and running in my docker container. My `pyproject.toml` and `.baseline` are present in the container and are correct. 
Running locally gets no errors - running in the container gives many _many_ errors. 

`flakehell plugins` accurately reflects the `pyproject.toml` - I can update the confifg and the output of both `plugins` and `lint` is updated accordingly.

How can I figure out why it's not reading the baseline? 
`pyproject.toml` as above in original issue

**Comment by jurasikasan** [comment]
Hey!
I am still able to reproduce this effect without usage of any workarounds,
```
docker run -it python:3.7.6 bash
---(in another terminal) sudo docker cp <proj_root_path> <container_name>:/
cd <proj_root_path> 
python3 -m pip install flakehell
flakehell lint
```

This is clear run as per docs.. (this is a bug in my vision, even though maintainers of the fakehell might be not guilty, but still in their power to fix it). 
So my opinion - this issue should be reopened, it is still reproducible and should be important for maintainers... 

About your problem.. Since computers are machines and any thing which worked before and doesn't work now just a diff - try to find your diff between last successful pipeline and first failed (broken one because of root of this issue)
Diff going to be (as I got it) between versions of dependencies, so you (theoretically) should get 'standard' flow of process fixing/freezing/holding last successful versions of dependencies.
like (my exact case):
python3 -m pip install flake8==3.7.9
python3 -m pip install pyflakes==2.1.1
python3 -m pip install pycodestyle==2.5.0
 ... and finally..
python3 -m pip install flakehell

P.S.
Hope, it will help you, but don't expect too much, I'm just a user of fakehell, if it doesn't work for you anymore - not sure if I can help with, sorry.. Kind of shared what helped me. I'v tried..
P.P.S
Issie relevant imo..

**Comment by Phil-Barber** [comment]
Thanks!

**Comment by orsinium** [comment]
Thank you for the report! Please, upgrade flakehell to 0.3.4.
