### ISSUE TITLE
flake8 >= 3.8 support

### ISSUE THREAD

**Issue by jnoortheen** [life4/flakehell#56]
using `flakehell` with `flake8>=3.8 ` raises error

```
 ❯ flakehell lint                                                                                                            
Traceback (most recent call last):
  File ".venv/bin/flakehell", line 10, in <module>
    sys.exit(entrypoint())
  File ".venv/lib/python3.8/site-packages/flakehell/_cli.py", line 39, in entrypoint
    exit_code, msg = main(argv)
  File ".venv/lib/python3.8/site-packages/flakehell/_cli.py", line 31, in main
    return COMMANDS[command_name](argv=argv[1:])
  File ".venv/lib/python3.8/site-packages/flakehell/commands/_lint.py", line 11, in lint_command
    app.run(argv)
  File ".venv/lib/python3.8/site-packages/flake8/main/application.py", line 360, in run
    self._run(argv)
  File ".venv/lib/python3.8/site-packages/flake8/main/application.py", line 347, in _run
    self.initialize(argv)
  File ".venv/lib/python3.8/site-packages/flake8/main/application.py", line 328, in initialize
    self.find_plugins(config_finder)
TypeError: find_plugins() takes 1 positional argument but 2 were given

```

**Comment by orsinium** [comment]
Thank you for the report! Please, upgrade flakehell to 0.3.4.
